# Generated by Django 5.2 on 2025-06-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_temporaryuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='amount_orders',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
